// Generated by Skyramp v1.3.29 on 2026-06-25 18:57:00.582757687 +0000 UTC m=+287.633949179
// Command: skyramp generate contract rest http://localhost:8093/api/v2/deployment/counts \
// 		--auth-header Coder-Session-Token \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output deployment_counts_contract_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-data {"pending":0,"building":0,"running":0,"failed":0,"stopped":0} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8093");

// contract test for /api/v2/deployment/counts GET
test('testCountsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Coder-Session-Token"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedCountsGetResponseBody: string = `{
        "building": 0,
        "failed": 0,
        "pending": 0,
        "running": 0,
        "stopped": 0
    }`;

    // Execute Request
    const countsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/deployment/counts",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(countsGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(countsGetResponse, expectedCountsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(countsGetResponse, "building"), 'value').not.toBeNull();
    expect(getResponseValue(countsGetResponse, "failed"), 'value').not.toBeNull();
    expect(getResponseValue(countsGetResponse, "pending"), 'value').not.toBeNull();
    expect(getResponseValue(countsGetResponse, "running"), 'running').not.toBeNull();
    expect(getResponseValue(countsGetResponse, "stopped"), 'stopped').not.toBeNull();
    expect(getResponseValue(countsGetResponse, "pending"), 'pending range').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(countsGetResponse, "building"), 'building range').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(countsGetResponse, "running"), 'running range').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(countsGetResponse, "failed"), 'failed range').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(countsGetResponse, "stopped"), 'stopped range').toBeGreaterThanOrEqual(0);
});
