// Generated by Skyramp v1.3.29 on 2026-06-25 18:57:11.777800399 +0000 UTC m=+298.828991901
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output deployment_stats_and_counts_integration_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/coder/coder/tests/skyramp/scenario_deployment-stats-and-counts.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8093");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    const authToken = process.env.SKYRAMP_TEST_TOKEN || "SKYRAMP_PLACEHOLDER_TOKEN";
    const authHeaders = {"Coder-Session-Token": authToken};

    // Execute Request
    let statsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v2/deployment/stats",
        method:"GET",
        headers:authHeaders
    });

    // Generated Assertions
    expect(statsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(statsGetResponse, "workspaces.pending"), 'workspaces.pending range').toBeGreaterThanOrEqual(0);
    expect(getValue(statsGetResponse, "workspaces.building"), 'workspaces.building range').toBeGreaterThanOrEqual(0);
    expect(getValue(statsGetResponse, "workspaces.running"), 'workspaces.running range').toBeGreaterThanOrEqual(0);
    expect(getValue(statsGetResponse, "workspaces.failed"), 'workspaces.failed range').toBeGreaterThanOrEqual(0);
    expect(getValue(statsGetResponse, "workspaces.stopped"), 'workspaces.stopped range').toBeGreaterThanOrEqual(0);

    // Execute Request
    let countsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v2/deployment/counts",
        method:"GET",
        headers:authHeaders
    });

    // Generated Assertions
    expect(countsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(countsGetResponse, "pending"), 'pending').not.toBeNull();
    expect(getValue(countsGetResponse, "building"), 'building').not.toBeNull();
    expect(getValue(countsGetResponse, "running"), 'running').not.toBeNull();
    expect(getValue(countsGetResponse, "failed"), 'failed').not.toBeNull();
    expect(getValue(countsGetResponse, "stopped"), 'stopped').not.toBeNull();
    expect(getValue(countsGetResponse, "pending"), 'pending range').toBeGreaterThanOrEqual(0);
    expect(getValue(countsGetResponse, "building"), 'building range').toBeGreaterThanOrEqual(0);
    expect(getValue(countsGetResponse, "running"), 'running range').toBeGreaterThanOrEqual(0);
    expect(getValue(countsGetResponse, "failed"), 'failed range').toBeGreaterThanOrEqual(0);
    expect(getValue(countsGetResponse, "stopped"), 'stopped range').toBeGreaterThanOrEqual(0);
});

