// Generated by Skyramp v1.3.29 on 2026-06-25 18:57:24.576915026 +0000 UTC m=+311.628106517
// Command: skyramp generate contract rest http://localhost:8093/api/v2/deployment/counts \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output deployment_counts_unauth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8093");

// contract test for /api/v2/deployment/counts GET
test('testCountsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const countsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/deployment/counts",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(countsGetResponse.statusCode, 'status code').toBe(401);
    expect(getResponseValue(countsGetResponse, "message"), 'message').not.toBeNull();
});
