// Generated by Skyramp v1.3.29 on 2026-06-25 19:25:17.760176429 +0000 UTC m=+411.118234959
// Command: skyramp generate contract rest http://localhost:3111/api/v2/ \
// 		--api-schema coderd/apidoc/swagger.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output api_root_contract_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp/coder-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3111");

// contract test for /api/v2/ GET
test('testV2Get', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedV2GetResponseBody: string = `{
        "detail": "string",
        "message": "string",
        "validations": [
            {
                "detail": "string",
                "field": "string"
            }
        ]
    }`;

    // Execute Request
    const v2GetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(v2GetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(v2GetResponse, expectedV2GetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(v2GetResponse, "detail"), 'value').not.toBeNull();
    expect(getResponseValue(v2GetResponse, "message"), 'value').not.toBeNull();
    expect(getResponseValue(v2GetResponse, "validations.0.detail"), 'value').not.toBeNull();
});
