// Generated by Skyramp v1.3.29 on 2026-06-25 19:25:14.705507453 +0000 UTC m=+408.063566003
// Command: skyramp generate contract rest http://localhost:3111/api/v2/buildinfo \
// 		--api-schema coderd/apidoc/swagger.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output buildinfo_contract_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp/coder-backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3111");

// contract test for /api/v2/buildinfo GET
test('testBuildinfoGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedBuildinfoGetResponseBody: string = `{
        "agent_api_version": "1.0",
        "dashboard_url": "http://localhost:3111",
        "deployment_id": "00000000-0000-0000-0000-000000000001",
        "external_url": "https://github.com/coder/coder",
        "go_version": "go1.26.4",
        "provisioner_api_version": "1.0",
        "telemetry": false,
        "upgrade_message": "",
        "version": "v2.0.0",
        "webpush_public_key": "",
        "workspace_proxy": false
    }`;

    // Execute Request
    const buildinfoGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/buildinfo",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(buildinfoGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(buildinfoGetResponse, expectedBuildinfoGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(buildinfoGetResponse, "agent_api_version"), 'value').not.toBeNull();
    expect(getResponseValue(buildinfoGetResponse, "dashboard_url"), 'value').not.toBeNull();
    expect(getResponseValue(buildinfoGetResponse, "deployment_id"), 'value').not.toBeNull();
    expect(getResponseValue(buildinfoGetResponse, "go_version"), 'go_version').not.toBeNull();
    expect(getResponseValue(buildinfoGetResponse, "go_version"), 'go_version format').toMatch(/^go\d+\.\d+/);
    expect(getResponseValue(buildinfoGetResponse, "workspace_proxy"), 'workspace_proxy').toBe(false);
    expect(getResponseValue(buildinfoGetResponse, "telemetry"), 'telemetry').toBe(false);
    expect(getResponseValue(buildinfoGetResponse, "deployment_id"), 'deployment_id format').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(buildinfoGetResponse, "dashboard_url"), 'dashboard_url format').toMatch(/^https?:\/\//);
    expect(getResponseValue(buildinfoGetResponse, "version"), 'version').not.toBeNull();
});
