// Generated by Skyramp v1.3.29 on 2026-06-25 19:25:43.677994994 +0000 UTC m=+437.036053545
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output buildinfo_updatecheck_version_workflow_integration_test.spec.ts \
// 		--output-dir /home/runner/work/coder/coder/tests/skyramp/coder-backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/coder/coder/tests/skyramp/coder-backend/scenario_buildinfo_updatecheck_version_workflow.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3111");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let buildinfoGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v2/buildinfo",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(buildinfoGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(buildinfoGetResponse, "go_version"), 'go_version').not.toBeNull();
    expect(getValue(buildinfoGetResponse, "go_version"), 'go_version format').toMatch(/^go\d+\.\d+/);
    expect(getValue(buildinfoGetResponse, "workspace_proxy"), 'workspace_proxy').toBe(false);
    expect(getValue(buildinfoGetResponse, "telemetry"), 'telemetry').toBe(false);
    expect(getValue(buildinfoGetResponse, "deployment_id"), 'deployment_id format').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(buildinfoGetResponse, "version"), 'version').not.toBeNull();

    // Execute Request
    let updatecheckGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v2/updatecheck",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(updatecheckGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(updatecheckGetResponse, "current"), 'current').toBe(true);
    expect(getValue(updatecheckGetResponse, "version"), 'version').not.toBeNull();
});

